CREATE TABLE tblquotes (
    qid BIGINT NOT NULL AUTO_INCREMENT,
    quote_number VARCHAR(80) NOT NULL,
    quote_type VARCHAR(80) NULL,
    project_number VARCHAR(80) NULL,
    create_date DATE NOT NULL,
    submit_date DATE NULL,
    -- tblcustomers.cust_id and tblcontacts.cont_id are BIGINT UNSIGNED, so the
    -- referencing columns have to match exactly or MySQL rejects the FK.
    cust_id BIGINT UNSIGNED NULL,
    customer_name VARCHAR(200) NULL,
    cont_id BIGINT UNSIGNED NULL,
    contact_name VARCHAR(200) NULL,
    customer_rfq VARCHAR(120) NULL,
    nc_id BIGINT NULL,
    nc_number VARCHAR(80) NULL,
    assy_number VARCHAR(120) NULL,
    pcb_number VARCHAR(120) NULL,
    assy_quote_status VARCHAR(80) NULL,
    assy_quote_person VARCHAR(200) NULL,
    pcb_quote_number VARCHAR(120) NULL,
    pcb_quote_status VARCHAR(80) NULL,
    pcb_quote_person VARCHAR(200) NULL,
    quote_array VARCHAR(80) NULL,
    sales_percentage DECIMAL(6, 2) NULL,
    internal_note1 TEXT NULL,
    internal_note2 TEXT NULL,
    notes_to_customer TEXT NULL,
    other_nre_charges VARCHAR(200) NULL,
    received_date DATE NULL,
    pnc_notes TINYINT(1) NOT NULL DEFAULT 0,
    labor_only TINYINT(1) NOT NULL DEFAULT 0,
    parts_scheduled TINYINT(1) NOT NULL DEFAULT 0,
    feedback TINYINT(1) NOT NULL DEFAULT 0,
    itarc TINYINT(1) NOT NULL DEFAULT 0,
    berryc TINYINT(1) NOT NULL DEFAULT 0,
    pcba_plant VARCHAR(120) NULL,
    pcb_origin VARCHAR(120) NULL,
    status VARCHAR(80) NULL,
    created_by_user_id BIGINT NULL,
    created_at DATETIME NOT NULL,
    updated_by_user_id BIGINT NULL,
    updated_at DATETIME NULL,
    is_deleted TINYINT(1) NOT NULL DEFAULT 0,
    PRIMARY KEY (qid),
    UNIQUE KEY uk_quote_number (quote_number),
    KEY idx_quotes_customer (cust_id),
    KEY idx_quotes_nc (nc_id),
    CONSTRAINT fk_quote_customer FOREIGN KEY (cust_id) REFERENCES tblcustomers (cust_id) ON DELETE SET NULL,
    CONSTRAINT fk_quote_contact FOREIGN KEY (cont_id) REFERENCES tblcontacts (cont_id) ON DELETE SET NULL,
    CONSTRAINT fk_quote_nc FOREIGN KEY (nc_id) REFERENCES tblnc_masters (nc_id) ON DELETE SET NULL,
    CONSTRAINT fk_quote_created_by FOREIGN KEY (created_by_user_id) REFERENCES tblusers (user_id) ON DELETE SET NULL,
    CONSTRAINT fk_quote_updated_by FOREIGN KEY (updated_by_user_id) REFERENCES tblusers (user_id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE tblquote_quantities (
    qty_id BIGINT NOT NULL AUTO_INCREMENT,
    qid BIGINT NOT NULL,
    lt VARCHAR(40) NULL,
    lt_pcb INT NULL,
    lt_pcba INT NULL,
    qty INT NULL,
    pcb_cost DECIMAL(12, 2) NULL,
    parts_cost DECIMAL(12, 2) NULL,
    labor_cost DECIMAL(12, 2) NULL,
    labor_discount DECIMAL(6, 2) NULL,
    part_markup DECIMAL(6, 2) NULL,
    testing DECIMAL(12, 2) NULL,
    conf_coat DECIMAL(12, 2) NULL,
    service_name VARCHAR(120) NULL,
    service_charge VARCHAR(80) NULL,
    sub_total DECIMAL(12, 2) NULL,
    total_sales_pct DECIMAL(12, 2) NULL,
    pcb_nre DECIMAL(12, 2) NULL,
    assy_nre DECIMAL(12, 2) NULL,
    stencil DECIMAL(12, 2) NULL,
    other_nre DECIMAL(12, 2) NULL,
    total DECIMAL(12, 2) NULL,
    comments TEXT NULL,
    received TINYINT(1) NOT NULL DEFAULT 0,
    PRIMARY KEY (qty_id),
    KEY idx_quote_quantities_qid (qid),
    CONSTRAINT fk_quote_quantity_quote FOREIGN KEY (qid) REFERENCES tblquotes (qid) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE tblquote_history (
    qh_id BIGINT NOT NULL AUTO_INCREMENT,
    qid BIGINT NOT NULL,
    action VARCHAR(20) NOT NULL,
    status VARCHAR(80) NULL,
    assy_quote_status VARCHAR(80) NULL,
    pcb_quote_status VARCHAR(80) NULL,
    changed_by_user_id BIGINT NULL,
    changed_by_name VARCHAR(200) NOT NULL,
    changed_at DATETIME NOT NULL,
    PRIMARY KEY (qh_id),
    KEY idx_quote_history_qid (qid, changed_at),
    CONSTRAINT fk_quote_history_quote FOREIGN KEY (qid) REFERENCES tblquotes (qid) ON DELETE CASCADE,
    CONSTRAINT fk_quote_history_user FOREIGN KEY (changed_by_user_id) REFERENCES tblusers (user_id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE tblquote_locks (
    qid BIGINT NOT NULL,
    locked_by_user_id BIGINT NOT NULL,
    acquired_at DATETIME NOT NULL,
    last_seen_at DATETIME NOT NULL,
    PRIMARY KEY (qid),
    KEY idx_quote_locks_user (locked_by_user_id),
    CONSTRAINT fk_quote_lock_quote FOREIGN KEY (qid) REFERENCES tblquotes (qid) ON DELETE CASCADE,
    CONSTRAINT fk_quote_lock_user FOREIGN KEY (locked_by_user_id) REFERENCES tblusers (user_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
